<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Charlies-MBP.home" ignored="0" name="Command line test" tests="2" failures="1" timestamp="2020-03-05T10:45:08 CST" time="0.116" errors="0">
  <testcase name="testHelloJenkins" time="0.018" classname="com.perscholas.jenkins_hello.testng.HelloJenkinsTest"/>
  <testcase name="testHelloJenkinsAgain" time="0.024" classname="com.perscholas.jenkins_hello.testng.HelloJenkinsTest">
    <failure type="java.lang.AssertionError" message="expected [Hello Jenkins again] but found [Hello Jenkins again!!!]">
      <![CDATA[java.lang.AssertionError: expected [Hello Jenkins again] but found [Hello Jenkins again!!!]
at com.perscholas.jenkins_hello.testng.HelloJenkinsTest.testHelloJenkinsAgain(HelloJenkinsTest.java:24)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 41 stack frames]]>
    </failure>
  </testcase> <!-- testHelloJenkinsAgain -->
</testsuite> <!-- Command line test -->
